/* eslint-disable quotes */
export const queryTit2_15_3_1 = {
  title: "unfoldingWord® Simplified Text",
  version: "38",
  resourceLink: "unfoldingWord/en/ust/master",
  server: "https://git.door43.org",
  branch: "master",
  book: {
    tit: {
      ch: {
        2: {
          v: {
            15: { verseObjects: [] },
          },
        },
        3: {
          V: {
            1: { verseObjects: [] },
          },
        },
      },
    },
  },
};

export const mockResultTit2_15_3_1 = {
  title: "unfoldingWord® Simplified Text",
  version: "38",
  resourceLink: "unfoldingWord/en/ust/master",
  server: "https://git.door43.org",
  branch: "master",
  url:
    "https://git.door43.org/api/v1/repos/unfoldingWord/en_ust/contents/57-TIT.usfm?ref=master",
  book: {
    tit: {
      ch: {
        2: {
          v: {
            15: {
              verseObjects: [
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G29800",
                  lemma: "λαλέω",
                  morph: "Gr,V,MPA2,,S,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "λάλει",
                  children: [
                    {
                      text: "Titus",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: ", ",
                    },
                    {
                      text: "speak",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "about",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G37780",
                  lemma: "οὗτος",
                  morph: "Gr,RD,,,,ANP,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ταῦτα",
                  children: [
                    {
                      text: "these",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "things",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ". ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G38700",
                  lemma: "παρακαλέω",
                  morph: "Gr,V,MPA2,,S,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "παρακάλει",
                  children: [
                    {
                      text: "Urge",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "the",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "believers",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "to",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "3",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "live",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "as",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "I",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "have",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "described",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G25320",
                  lemma: "καί",
                  morph: "Gr,CC,,,,,,,,",
                  occurrence: "2",
                  occurrences: "2",
                  content: "καὶ",
                  children: [
                    {
                      text: "and",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G16510",
                  lemma: "ἐλέγχω",
                  morph: "Gr,V,MPA2,,S,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ἔλεγχε",
                  children: [
                    {
                      text: "correct",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "them",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "2",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "when",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "they",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "do",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "not",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ", ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G33260",
                  lemma: "μετά",
                  morph: "Gr,P,,,,,G,,,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "μετὰ",
                  children: [
                    {
                      text: "using",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G39560",
                  lemma: "πᾶς",
                  morph: "Gr,EQ,,,,GFS,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "πάσης",
                  children: [
                    {
                      tag: "zaln",
                      type: "milestone",
                      strong: "G20030",
                      lemma: "ἐπιταγή",
                      morph: "Gr,N,,,,,GFS,",
                      occurrence: "1",
                      occurrences: "1",
                      content: "ἐπιταγῆς",
                      children: [
                        {
                          text: "your",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "right",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "to",
                          tag: "w",
                          type: "word",
                          occurrence: "2",
                          occurrences: "3",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "command",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "them",
                          tag: "w",
                          type: "word",
                          occurrence: "2",
                          occurrences: "2",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "if",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "necessary",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                      ],
                      endTag: "zaln-e\\*",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ". ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G33670",
                  lemma: "μηδείς",
                  morph: "Gr,RI,,,,NMS,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "μηδείς",
                  children: [
                    {
                      tag: "zaln",
                      type: "milestone",
                      strong: "G47710",
                      lemma: "σύ",
                      morph: "Gr,RP,,,2G,S,",
                      occurrence: "1",
                      occurrences: "1",
                      content: "σου",
                      children: [
                        {
                          tag: "zaln",
                          type: "milestone",
                          strong: "G40650",
                          lemma: "περιφρονέω",
                          morph: "Gr,V,MPA3,,S,",
                          occurrence: "1",
                          occurrences: "1",
                          content: "περιφρονείτω",
                          children: [
                            {
                              text: "Make",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "sure",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "that",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "everyone",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "pays",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "attention",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "to",
                              tag: "w",
                              type: "word",
                              occurrence: "3",
                              occurrences: "3",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "what",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "you",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                            {
                              type: "text",
                              text: " ",
                            },
                            {
                              text: "say",
                              tag: "w",
                              type: "word",
                              occurrence: "1",
                              occurrences: "1",
                            },
                          ],
                          endTag: "zaln-e\\*",
                        },
                      ],
                      endTag: "zaln-e\\*",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ".\n\n",
                },
                {
                  tag: "ts\\*",
                  nextChar: "\n",
                },
              ],
            },
          },
        },
        3: {
          V: {
            1: {
              verseObjects: [
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G52790",
                  lemma: "ὑπομιμνῄσκω",
                  morph: "Gr,V,MPA2,,S,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ὑπομίμνῃσκε",
                  children: [
                    {
                      text: "Titus",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: ", ",
                    },
                    {
                      text: "continue",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "to",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "3",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "tell",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G08460",
                  lemma: "αὐτός",
                  morph: "Gr,RP,,,3AMP,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "αὐτοὺς",
                  children: [
                    {
                      text: "our",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "people",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "2",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G52790",
                  lemma: "ὑπομιμνῄσκω",
                  morph: "Gr,V,MPA2,,S,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ὑπομίμνῃσκε",
                  children: [
                    {
                      text: "again",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G52930",
                  lemma: "ὑποτάσσω",
                  morph: "Gr,V,NPM,,,,,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ὑποτάσσεσθαι",
                  children: [
                    {
                      tag: "zaln",
                      type: "milestone",
                      strong: "G39800",
                      lemma: "πειθαρχέω",
                      morph: "Gr,V,NPA,,,,,",
                      occurrence: "1",
                      occurrences: "1",
                      content: "πειθαρχεῖν",
                      children: [
                        {
                          text: "that",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "they",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "2",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "should",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "obey",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                      ],
                      endTag: "zaln-e\\*",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G07460",
                  lemma: "ἀρχή",
                  morph: "Gr,N,,,,,DFP,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ἀρχαῖς",
                  children: [
                    {
                      tag: "zaln",
                      type: "milestone",
                      strong: "G18490",
                      lemma: "ἐξουσία",
                      morph: "Gr,N,,,,,DFP,",
                      occurrence: "1",
                      occurrences: "1",
                      content: "ἐξουσίαις",
                      children: [
                        {
                          text: "the",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "people",
                          tag: "w",
                          type: "word",
                          occurrence: "2",
                          occurrences: "2",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "who",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "rule",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "over",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "them",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                      ],
                      endTag: "zaln-e\\*",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ". ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G15100",
                  lemma: "εἰμί",
                  morph: "Gr,V,NPA,,,,,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "εἶναι",
                  children: [
                    {
                      text: "They",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "need",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "to",
                      tag: "w",
                      type: "word",
                      occurrence: "2",
                      occurrences: "3",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "be",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G20920",
                  lemma: "ἕτοιμος",
                  morph: "Gr,NP,,,,AMP,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ἑτοίμους",
                  children: [
                    {
                      text: "ready",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G20410",
                  lemma: "ἔργον",
                  morph: "Gr,N,,,,,ANS,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ἔργον",
                  children: [
                    {
                      text: "to",
                      tag: "w",
                      type: "word",
                      occurrence: "3",
                      occurrences: "3",
                    },
                    {
                      type: "text",
                      text: " ",
                    },
                    {
                      text: "do",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G00180",
                  lemma: "ἀγαθός",
                  morph: "Gr,AA,,,,ANS,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "ἀγαθὸν",
                  children: [
                    {
                      text: "good",
                      tag: "w",
                      type: "word",
                      occurrence: "1",
                      occurrences: "1",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: " ",
                },
                {
                  tag: "zaln",
                  type: "milestone",
                  strong: "G43140",
                  lemma: "πρός",
                  morph: "Gr,P,,,,,A,,,",
                  occurrence: "1",
                  occurrences: "1",
                  content: "πρὸς",
                  children: [
                    {
                      tag: "zaln",
                      type: "milestone",
                      strong: "G39560",
                      lemma: "πᾶς",
                      morph: "Gr,EQ,,,,ANS,",
                      occurrence: "1",
                      occurrences: "1",
                      content: "πᾶν",
                      children: [
                        {
                          text: "whenever",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "they",
                          tag: "w",
                          type: "word",
                          occurrence: "2",
                          occurrences: "2",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "are",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                        {
                          type: "text",
                          text: " ",
                        },
                        {
                          text: "able",
                          tag: "w",
                          type: "word",
                          occurrence: "1",
                          occurrences: "1",
                        },
                      ],
                      endTag: "zaln-e\\*",
                    },
                  ],
                  endTag: "zaln-e\\*",
                },
                {
                  type: "text",
                  text: ".\n",
                },
              ],
            },
          },
        },
      },
    },
  },
};
